baseURL: https://jpetersmam2023.netlify.app/
languageCode: en-us
title: JF Peters
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get started
    enable:: yes
    subtitle: |-
      Welcome to my website which gives a bit of context on my interests and my projects
    title: Jean-Francois Peters 
    url: blogs
  blog: {}
  contact:
    address:
      - city: London,W9
        country: United Kingdom
        street: Maida Vale 03 
        title: Adress
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jpeters.mam2023@london.edu 
        title: Emails
    enable: yes
    phone:
      - phone: (+32) 478-116-587 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: JF Peters
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/jeanfrancois.peters.9/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/jf.peters._/
      - icon: fa-github
        label: GitHub
        url: https://github.com/jpeters2023
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jean-francois-p%C3%A9ters-175016153
  image: ''
  name: Your name
  navigation:
    button1:
      - name: My Biography
        url: blogs/biography
    button2:
      - name: Pictures
        url: blogs/pictures
    links:
      - name: CV 
        url: '#'
      - name: Books to read
        url: blogs
      - name: Brexit Analysis
        url: blogs/brexit
      - name: Le Wagon final project
        url: elements.html
    menu: Quick Navigation
    subtitle: Peters
    title: Jean Francois
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: A little explanation on how I ended up at LBS 
        title: My Biography
        url: blogs/biography
      - image: pic02.jpg
        subtitle: Click here to access my professional and acedemic experience
        title: CV
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: An analysis inspired by an homework done on Brexit data
        title: Brexit Analysis
        url: blogs/brexit
      - image: pic04.jpg
        subtitle: My final project I did for my data science bootcamp at Le Wagon
        title: Le Wagon
        url: blogs/lewagon
      - image: books.jpg
        subtitle: A list of books I want to read 
        title: Books
        url: blogs/books
      - image: pictures.jpg
        subtitle: "10 Pictures of my life"
        title: Pictures
        url: blogs/pictures
  two:
    buttonText: Content menu
    enable: yes
    subtitle: "This website is an assignment that was done for the Applied Statistics course, given by Kostis Christodoulou, during my Masters in Analytics
    at the London Business School.\n\nPress on the button below to access the contents made available on my webpage in the form of a list"
  
    title: A little bit of explanation 
    url: blogs
